import type { Metadata } from "next";
import ThemeProvider from "@/components/theme/theme-provider";
import { ThemeScript } from "@/components/theme/theme-script";
import "./globals.css";
import React from "react";
import Navbar from "@/components/ui/hero/navbar/Navbar";
import Footer from "@/components/sections/home/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
    <head>
        <ThemeScript />
    </head>
      <body
        className={`antialiased bg-white dark:bg-gray-900 text-gray-900 dark:text-gray-100`}
      >
      <ThemeProvider>
        <Navbar/>
          {children}
        <Footer/>
      </ThemeProvider>
      </body>
    </html>
  );
}
